// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://louzfpyptctawwkmulbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdXpmcHlwdGN0YXd3a211bGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjUxMTcsImV4cCI6MjA2OTQwMTExN30.wyIibf10VzVJST32EeqaJBtfxtSoAvS3nwFdalDluVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});